# Generated by Django 3.0.3 on 2020-02-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musclegroup',
            options={'verbose_name': 'MuscleGroup', 'verbose_name_plural': 'MuscleGroups'},
        ),
    ]
