# Generated by Django 3.0.3 on 2020-02-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='primary_equip_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='gym_plan.Equipment'),
        ),
    ]
