# Generated by Django 3.0.3 on 2020-02-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_plan', '0002_auto_20200217_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
    ]
