# Generated by Django 3.0.3 on 2020-02-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_plan', '0003_auto_20200217_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='icon_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='img_url',
            field=models.TextField(null=True),
        ),
    ]
