# Generated by Django 3.0.3 on 2020-02-17 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('gym_plan', '0005_auto_20200217_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(verbose_name=0)),
                ('repeat_count', models.PositiveIntegerField(verbose_name=0)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('creator_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='gym_plan.Set')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='exercises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_plan.Exercise'),
        ),
    ]
